name: develop CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get Github Repository
        uses: actions/checkout@v4

      - name: install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: create application.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: test and build
        run: ./gradlew clean build

      - name: change build file name
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: send build file to EC2 with SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ec2-user/yesable_server/tobe

      - name: connect to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            envs: APPLICATION_PROPERTIES
            script_stop: true
            script: |
              rm -rf /home/ec2-user/yesable_server/current
              mkdir /home/ec2-user/yesable_server/current
              mv /home/ec2-user/yesable_server/tobe/project.jar /home/ec2-user/yesable_server/current/project.jar
              cd /home/ec2-user/yesable_server/current
              sudo fuser -k -n tcp 8081 || true
              nohup java -jar project.jar --spring.profiles.active=local > ~/yesable_server/logs/server.log 2>&1 &
              rm -rf /home/ec2-user/yesable_server/tobe