name: develop CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: connect to EC2 with SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES : ${{ secrets.APPLICATION_PROPERTIES }}
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            envs: APPLICATION_PROPERTIES
            script_stop: true
            script: |
              cd /home/ec2-user/yesable_server/
              rm -rf src/main/resources/application.yml
              git pull origin main
              echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yml
              ./gradlew clean build
              sudo fuser -k -n tcp 8081 || true 
              nohup java -jar build/libs/*SNAPSHOT.jar --spring.profiles.active=local > ~/yesable_server/logs/server.log 2>&1 &